# Uncomment the next line to define a global platform for your project
platform :ios, '9.1'

target 'Clynica' do
  pod 'GoogleSignIn'
  pod 'MyScriptInteractiveInk-Runtime'
  pod 'MyScriptInteractiveInk-UIReferenceImplementation', :path => '.'

end
