# Uncomment the next line to define a global platform for your project
platform :ios, '9.1'

target 'ClynicaApp' do
  pod 'GoogleSignIn'
  pod 'MyScriptInteractiveInk-Runtime'
  pod 'MyScriptInteractiveInk-UIReferenceImplementation', :path => '.'
  pod 'MaterialComponents'
  pod 'TextFieldEffects'

end
